### PR TITLE
(Chore) Prepare apps to MongoDB 7 :: GoodServer

### PR DESCRIPTION
**Pull request by johnsmith-gooddollar**
# Description

- bumps mongoose to the latest version (using latest mongo client)
- bumps jest-environment-node to fix "ReferenceError: AbortController is not defined" unit tests error according to this suggestion https://github.com/facebook/create-react-app/issues/11626#issuecomment-970282921

About #443 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [x] @mentions of the person or team responsible for reviewing proposed changes

### CODE REVIEW

**Review by sirpy — CHANGES_REQUESTED** [review]
1. dont change logic of isdupuserdata
2. fix failing tests

**Comment by johnsmith-gooddollar** [comment]
> * dont change logic of isdupuserdata
> * fix failing tests

the logic was wrong. if we have email, phone was ignored. the corresponding unit test was failing

**Comment by johnsmith-gooddollar** [comment]
tests fixed

**Comment by sirpy** [comment]
@johnsmith-gooddollar the isdup logic expects only either mobile or email not both. please restore the way it was. if the test needs to be adapted change it, but do not change the logic

**Comment by johnsmith-gooddollar** [comment]
@sirpy done

**Pull request merged**
