### PR TITLE
(Chore) 550 setup heroku webworkers

### PR DESCRIPTION
**Pull request by AlexeyKosinski**
# Description

- remove throng from server-dev.js
- move all imports into worker

So I made research and understood that is how should work throng.
it starts the whole top-level file first time and for each worker too. that's why we saw duplicates of logs

About #550 https://app.zenhub.com/workspaces/gooddollar-5d50833888a83c6880d3e345/issues/gooddollar/goodserver/130

# How Has This Been Tested?

restart dev server and look at the logs. U will see start workerId = 1 and start workerId = 2 logs

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request ( for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [x] @mentions of the person or team responsible for reviewing proposed changes

### CODE REVIEW

**Comment by sirpy** [comment]
keep the original index in es6 import format and export the start method, containing only code, no requires.
in the new index file start throng with the start function importing the start from the old index

**Comment by sirpy** [comment]
@AlexeyKosinski waiting for you updates

**Comment by AlexeyKosinski** [comment]
done. tested on gooddev.

**Comment by sirpy** [comment]
@AlexeyKosinski on heroku i spikes where server uses 380MB, so we need test this setup where we set the worker to 256.
See how you can recreate this load on gooddev. merge the PR once you are ready to test it.

**Pull request merged**
